create extension if not exists pgcrypto;

create table if not exists public.authenticated (
    id bigint generated by default as identity primary key,
    username text not null unique,
    email text not null unique,
    password_hash text not null,
    created_at timestamptz not null default now()
);

create table if not exists public.sessions (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.authenticated(id) on delete cascade,
    token text not null unique,
    created_at timestamptz not null default now(),
    expires_at timestamptz not null
);

create table if not exists public.login_events (
    id bigint generated by default as identity primary key,
    user_id bigint references public.authenticated(id) on delete set null,
    created_at timestamptz not null default now()
);

create table if not exists public.links (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.authenticated(id) on delete cascade,
    link_name text not null,
    link_description text not null default '',
    destination_link text not null,
    slug text not null unique,
    visits bigint not null default 0 check (visits >= 0),
    max_age_minutes integer check (max_age_minutes is null or max_age_minutes > 0),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    status text not null default 'active' check (status in ('active', 'deleted', 'expired')),
    access_code_hash text
);

create index if not exists idx_sessions_token on public.sessions(token);
create index if not exists idx_sessions_user_id on public.sessions(user_id);
create index if not exists idx_login_events_created_at on public.login_events(created_at);
create index if not exists idx_links_user_id on public.links(user_id);
create index if not exists idx_links_status on public.links(user_id, status);
create index if not exists idx_links_slug on public.links(slug);
create index if not exists idx_links_updated_at on public.links(user_id, updated_at desc);
create index if not exists idx_links_visits on public.links(user_id, visits desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists authenticated_updated_at on public.authenticated;
drop trigger if exists sessions_updated_at on public.sessions;
drop trigger if exists links_updated_at on public.links;

create trigger links_updated_at
before update on public.links
for each row execute function public.set_updated_at();

alter table public.authenticated enable row level security;
alter table public.sessions enable row level security;
alter table public.links enable row level security;
alter table public.login_events enable row level security;

drop policy if exists authenticated_service_role on public.authenticated;
drop policy if exists sessions_service_role on public.sessions;
drop policy if exists links_service_role on public.links;
drop policy if exists login_events_service_role on public.login_events;

create policy authenticated_service_role on public.authenticated
for all to service_role using (true) with check (true);

create policy sessions_service_role on public.sessions
for all to service_role using (true) with check (true);

create policy links_service_role on public.links
for all to service_role using (true) with check (true);

create policy login_events_service_role on public.login_events
for all to service_role using (true) with check (true);

comment on table public.authenticated is 'Application users for the FastAPI service';
comment on table public.sessions is 'Bearer sessions issued by the FastAPI service';
comment on table public.links is 'Short links and their lifecycle state';
